-- Preppin' Data 2023 Week 02 - International Bank Account Numbers
-- Source: TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK02_TRANSACTIONS
--         TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK02_SWIFT_CODES
--
-- Steps:
--   - Remove dashes from Sort Code
--   - Join to SWIFT lookup to get SWIFT_CODE and CHECK_DIGITS
--   - Construct IBAN: Country Code (GB) + Check Digits + SWIFT Code + Sort Code + Account Number
-- Output: TRANSACTION_ID, IBAN (100 rows)

SELECT
    t.TRANSACTION_ID,
    'GB' || s.CHECK_DIGITS || s.SWIFT_CODE || REPLACE(t.SORT_CODE, '-', '') || TO_VARCHAR(t.ACCOUNT_NUMBER) AS IBAN
FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK02_TRANSACTIONS t
JOIN TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK02_SWIFT_CODES s
    ON t.BANK = s.BANK
ORDER BY TRANSACTION_ID;
